"""Phase 5 atomic findings. Hand-labeled from independent human review text.

Each tuple is:
  pr, comment_id, seq, class, normalized_issue, file, line, status, notes, about_the_change
"""

from __future__ import annotations

# about_the_change False => never primary gold (out of scope / follow-up / optional nit
# the reviewer did not treat as required on this PR).
Atom = tuple[int, int, int, str, str, str, str, str, str, bool]

ATOMS: list[Atom] = [
    # 271
    (271, 3736623463, 1, "process_other", "Approval of the missing-RLock fix; no new issue raised.", "", "", "resolved", "complimentary", False),
    # 354
    (354, 3782222999, 1, "defect", "Adding RLock inside GetAlertsForTrip deadlocks: callers already hold staticMutex and RWMutex is not reentrant.", "internal/gtfs/gtfs_manager.go", "", "resolved", "", True),
    (354, 3782222999, 2, "design", "GetSituationIDsForTrip re-queries trip/route that GetAlertsForTrip already loaded.", "internal/restapi/trips_helper.go", "", "resolved", "reviewer marked pre-existing follow-up", False),
    (354, 3788071323, 1, "process_other", "Approval after the deadlock-inducing locks were removed.", "", "", "resolved", "complimentary", False),
    # 372
    (372, 3811930061, 1, "process_other", "Squash the branch into a single commit.", "", "", "resolved", "git process", False),
    (372, 3811930061, 2, "style", "Replace changelog-style mutex comments with what the lock protects, or delete them.", "internal/gtfs/advanced_direction_calculator.go", "", "resolved", "", False),
    (372, 3836860979, 1, "style", "Changelog-style mutex comments remain and were multiplied; remove or reword all four.", "internal/gtfs/advanced_direction_calculator.go", "", "resolved", "", False),
    (372, 3836860979, 2, "style", "Self-explanatory comment on empty RoutesForAgencyID return can be removed.", "internal/gtfs/gtfs_manager.go", "", "resolved", "", False),
    (372, 3836860979, 3, "style", "buildRouteIndex comments over-explain idiomatic Go; consider removing.", "internal/gtfs/static.go", "", "resolved", "optional", False),
    (372, 3838476457, 1, "defect", "Benchmark uses a hardcoded relative testdata path that breaks off-cwd; accept testing.TB in GetFixturePath.", "internal/gtfs/gtfs_manager_test.go", "", "resolved", "", True),
    (372, 3838476457, 2, "design", "Concurrent test locks manager.staticMutex directly instead of the public RLock API.", "internal/gtfs/gtfs_manager_test.go", "", "resolved", "", True),
    (372, 3838476457, 3, "style", "Single-threaded MapOptimization test takes unnecessary RLock around a local slice.", "internal/gtfs/gtfs_manager_test.go", "", "resolved", "", False),
    (372, 3838640779, 1, "process_other", "Final approval after all review items were addressed.", "", "", "resolved", "complimentary", False),
    # 457
    (457, 3838651608, 1, "design", "Redundant ValidateID after withID()/ValidateIDMiddleware; drop it to match other handlers.", "internal/restapi/routes_for_agency_handler.go", "", "resolved", "", True),
    (457, 3843869507, 1, "process_other", "Approval after redundant ValidateID was removed.", "", "", "resolved", "complimentary", False),
    # 507
    (507, 3976591136, 1, "design", "Add tests for the panic-recovery middleware.", "", "", "resolved", "", True),
    (507, 3871376685, 1, "defect", "recoveryResponseWriter must override Write(); implicit WriteHeader(200) bypasses wroteHeader and can concatenate a 500 onto an already-started 200.", "internal/restapi/recovery_middleware.go", "", "resolved", "", True),
    (507, 3871376685, 2, "design", "Log JSON encode failures on the panic-recovery path instead of discarding them.", "internal/restapi/recovery_middleware.go", "", "resolved", "", True),
    (507, 3871376685, 3, "design", "Add a panic(error) test so the error type-switch branch is covered.", "internal/restapi/recovery_middleware_test.go", "", "resolved", "", True),
    (507, 3871376685, 4, "design", "Optionally add method and request_id to the panic log.", "internal/restapi/recovery_middleware.go", "", "resolved", "reviewer marked optional", False),
    (507, 3885463432, 1, "design", "Recovery path writes through w instead of the wrapped rw; more consistent to write through rw.", "internal/restapi/recovery_middleware.go", "", "resolved", "reviewer marked optional", False),
    (507, 3885463432, 2, "design", "Optional test for panic after WriteHeader without Write.", "internal/restapi/recovery_middleware_test.go", "", "resolved", "reviewer marked optional", False),
    # 541
    (541, 3885566467, 1, "process_other", "Approval of two-phase locking; reviewer found no issues.", "", "", "resolved", "clean-change note", False),
    # 691
    (691, 3946787279, 1, "style", "Return nil instead of the fieldErrors map on the parseLocationParams happy path.", "internal/restapi/location_params.go", "", "resolved", "reviewer said cosmetic", False),
    (691, 3946787279, 2, "process_other", "Resolve merge conflicts with main before merging.", "", "", "resolved", "", False),
    (691, 3977929112, 1, "process_other", "Approval after nil-return and conflicts were addressed.", "", "", "resolved", "complimentary", False),
    # 702
    (702, 4061438413, 1, "process_other", "Rebase onto main and squash instead of merging main into the branch.", "", "", "resolved", "", False),
    (702, 3946924119, 1, "process_other", "Stops field addition is unrelated and should be a separate PR with OpenAPI alignment.", "internal/models/schedule_for_route.go", "", "resolved", "scope/process", False),
    (702, 3946924119, 2, "process_other", "Call out BeginTx context cancellation as a deliberate behavioral change in the description.", "gtfsdb/helpers.go", "", "resolved", "documentation of an intended change", False),
    (702, 3946924119, 3, "design", "Wrap BeginTx and Commit errors with the withTransaction label.", "gtfsdb/helpers.go", "", "resolved", "", True),
    (702, 3946924119, 4, "design", "Restore start/end LogOperation calls on bulkInsertCalendarDates.", "gtfsdb/helpers.go", "", "resolved", "", True),
    (702, 3946924119, 5, "design", "Document that a non-nil tx leaves rollback/commit to the caller.", "gtfsdb/helpers.go", "", "resolved", "", True),
    (702, 3949300658, 1, "process_other", "Approval after the first-round items were addressed.", "", "", "resolved", "complimentary", False),
    (702, 3977954040, 1, "process_other", "Approval after rebase; no remaining issues.", "", "", "resolved", "complimentary", False),
    # 756
    (756, 4010411899, 1, "process_other", "Approval of simplelru + mutex fix; reviewer found no issues.", "", "", "resolved", "clean-change note", False),
    # 1277
    (1277, 5230204795, 1, "process_other", "Claude-authored 'no issues found' comment posted by a human login.", "", "", "resolved", "complimentary / no issue", False),
    (1277, 3769501057, 1, "defect", "routeReferenceByID stamps the caller's agencyID instead of route.AgencyID, mis-prefixing cross-agency routes.", "internal/restapi/reference_utils.go", "", "resolved", "", True),
    (1277, 3769501069, 1, "design", "Skip GetRoute when the active route is already in routeRefs from stop references.", "internal/restapi/trip_for_vehicle_handler.go", "", "resolved", "", True),
    (1277, 3769501080, 1, "design", "Move parseIncludeParam to internal/utils with the other Parse* helpers.", "internal/restapi/trip_details_handler.go", "", "resolved", "", True),
    (1277, 3786346201, 1, "defect", "Cross-agency trip-for-vehicle omits the route's agency from references.Agencies.", "internal/restapi/trip_for_vehicle_handler.go", "", "resolved", "", True),
    (1277, 3786346205, 1, "style", "Replace the *bool pointer map with three explicit ParseBoolParam calls.", "internal/restapi/trip_details_handler.go", "", "resolved", "reviewer said not a bug", False),
    (1277, 4890748195, 1, "defect", "sql.ErrNoRows on a route reference lookup 404s the whole trip-for-vehicle request; log and skip the missing reference.", "internal/restapi/trip_for_vehicle_handler.go", "", "resolved", "", True),
    (1277, 4890748195, 2, "process_other", "Rebase after #1279/#1281 before landing.", "", "", "resolved", "", False),
    (1277, 4920186760, 1, "process_other", "Review summary pointing at inline comments; wiki note needs no code change.", "", "", "resolved", "pointer / spec note", False),
    (1277, 4940238409, 1, "process_other", "Summary of blocking inline plus a force-push process note.", "", "", "resolved", "process + pointer to inlines already labeled", False),
    # 1281
    (1281, 5230202557, 1, "process_other", "Claude-authored 'no issues found' comment posted by a human login.", "", "", "resolved", "", False),
    (1281, 4890748135, 1, "defect", "Merge with #1279 must thread schedule into buildTripForVehicleReferences or referencedStopIDs is silently dropped.", "internal/restapi/trip_for_vehicle_handler.go", "", "resolved", "", True),
    (1281, 4890748135, 2, "process_other", "Resolve merge conflicts with main.", "", "", "resolved", "", False),
    # 1286
    (1286, 5230225875, 1, "defect", "Per-trip serviceDate is not passed into BuildTripStatus, so status.serviceDate and schedule math stay on todayMidnight.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "", True),
    (1286, 5459087586, 1, "process_other", "Check-in: still blocked on merge conflicts.", "", "", "resolved", "", False),
    (1286, 5548030169, 1, "process_other", "Request for a CodeRabbit review.", "", "", "resolved", "", False),
    (1286, 5548284713, 1, "process_other", "Check-in: still dirty after conflicts and an open CodeRabbit thread.", "", "", "resolved", "", False),
    (1286, 3769940489, 1, "defect", "DUPLICATED trips outside the static window still fall back to todayMidnight for serviceDate.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "", True),
    (1286, 3769940493, 1, "style", "Extract the duplicated tripServiceDay lookup-with-fallback.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "", False),
    (1286, 3769940497, 1, "design", "Add a regression test for preferring today's null-block match over a previous-day same trip ID.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "", True),
    (1286, 4890748384, 1, "defect", "BuildTripStatus still receives todayMidnight while entry.ServiceDate uses the resolved day.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "same issue as 5230225875; kept as restatement", False),
    (1286, 4890748384, 2, "process_other", "Rebase onto current trips-for-route helpers.", "", "", "resolved", "", False),
    (1286, 4890748384, 3, "defect", "Null-block previous-day assignment overwrites today's midnight; block path lets today win.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "", True),
    (1286, 4920685807, 1, "process_other", "Review summary; unique code issues already on inlines.", "", "", "resolved", "", False),
    # 1288
    (1288, 5230223358, 1, "defect", "sql.ErrNoRows to 404 is unreachable for GetTripsByIDs and reintroduces a 404 the trips-for-route spec removed.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "", True),
    (1288, 5230223358, 2, "defect", "referencedTripIDs refactor is behavior-neutral so the new test does not demonstrate the empty-reference bug.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "", True),
    (1288, 3770121932, 1, "design", "referencedTripIDs is redundant with the presentTrips existence guard; append tripIDsToFetch in those guards.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "", True),
    (1288, 4890748411, 1, "defect", "Refactor does not fix #1287; reproducing case still missing.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "restates 5230223358-2", False),
    (1288, 4890748411, 2, "defect", "Dead ErrNoRows-to-404 reintroduces sendNotFound on this handler.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "restates 5230223358-1", False),
    (1288, 4890748411, 3, "design", "Escalating buildTripReferences DB failure to 500 reverses this handler's log-and-continue posture.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "", True),
    (1288, 4890748411, 4, "process_other", "Conflicts with main after stopIDMap was added.", "", "", "resolved", "", False),
    (1288, 4920893466, 1, "process_other", "Spec note: pre-existing 200-on-reference-failure is out of scope.", "", "", "resolved", "", False),
    (1288, 4920893466, 2, "design", "Pre-existing empty AgencyID when a placeholder route is not filled in.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "reviewer said out of scope", False),
    (1288, 4920893466, 3, "defect", "trip-details drop-on-not-found for synthetic DUPLICATED IDs can crash iOS.", "internal/restapi/trip_details_handler.go", "", "resolved", "reviewer said other handler / own issue", False),
    # 1296
    (1296, 5230230128, 1, "design", "Existing comment still says ParseTimeParameter ignores api.Clock; this PR makes that false.", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "", True),
    (1296, 5288280738, 1, "process_other", "Claude-authored 'no issues found' comment posted by a human login.", "", "", "resolved", "", False),
    (1296, 4890748270, 1, "defect", "Tests call createTestApiWithTripsForRouteFixture, which was removed on main; merge will not compile.", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "", True),
    (1296, 4890748270, 2, "design", "Stale comment that ParseTimeParameter ignores api.Clock.", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "same as 5230230128", False),
    (1296, 4890748270, 3, "process_other", "Title/description should not hide a shared-util signature change under test:.", "", "", "resolved", "", False),
    (1296, 4933040191, 1, "process_other", "Approval after rebase and comment fix.", "", "", "resolved", "complimentary", False),
    # 1298
    (1298, 5230227249, 1, "design", "references.trips assertions do not exercise the DUPLICATED fallback; the base trip is already statically active.", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "", True),
    (1298, 5288288278, 1, "process_other", "Claude-authored 'no issues found' comment posted by a human login.", "", "", "resolved", "", False),
    (1298, 5459087732, 1, "process_other", "Check-in: still blocked on merge conflicts.", "", "", "resolved", "", False),
    (1298, 4890748438, 1, "design", "references.trips block is tautological for the DUPLICATED path.", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "same as 5230227249", False),
    (1298, 4890748438, 2, "process_other", "Rebase onto createTestApiWithGTFSFixture; old fixture helper is gone.", "", "", "resolved", "", False),
    (1298, 4890748438, 3, "design", "includeStatus path and DUPLICATED/in_progress mapping are never asserted.", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "", True),
    (1298, 4890748438, 4, "design", "No list-length assertion, so extra entries would slip through.", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "", True),
    (1298, 4933041038, 1, "process_other", "Approval on merits but blocked on conflicts and another reviewer's change request.", "", "", "resolved", "", False),
    (1298, 4933041038, 2, "process_other", "PR description still describes helpers that are not in the current diff.", "", "", "resolved", "", False),
    # 1300
    (1300, 5230228349, 1, "design", "GreaterOrEqual(blockTripSequence, 0) cannot fail; assert the fixture's exact 0.", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "", True),
    (1300, 5288289436, 1, "process_other", "Claude-authored 'no issues found' comment posted by a human login.", "", "", "resolved", "", False),
    (1300, 5459087860, 1, "process_other", "Check-in: still blocked on merge conflicts.", "", "", "resolved", "", False),
    (1300, 5548284567, 1, "process_other", "Duplicate check-in on merge conflicts.", "", "", "resolved", "", False),
    (1300, 4890748463, 1, "design", "Vacuous BlockTripSequence assertion; use Equal(0, ...).", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "same as 5230228349", False),
    (1300, 4890748463, 2, "process_other", "Rebase onto createTestApiWithGTFSFixture.", "", "", "resolved", "", False),
    (1300, 4890748463, 3, "design", "Comment claims a SCHEDULED vehicle but never asserts Status/Phase.", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "", True),
    (1300, 4933041171, 1, "process_other", "Approval on merits blocked on conflicts and another reviewer.", "", "", "resolved", "", False),
    (1300, 4933041171, 2, "defect", "Helper takes a Clock but hardcodes tripsForRouteTestClock for RT timestamps, which can silently trip StaleDetector.", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "", True),
    (1300, 4933041171, 3, "style", "occupancyCount assertion message claims feed-omitted data; it pins a constructor default.", "internal/restapi/trips_for_route_handler_test.go", "", "resolved", "", False),
    (1300, 4933041171, 4, "process_other", "Coordinate with #1298 on overlapping realtime fixture helpers.", "", "", "resolved", "", False),
    # 1313
    (1313, 5227370818, 1, "defect", "situationCollector dedupes on agency-scoped IDs so one alert can appear twice at a multi-agency stop.", "internal/restapi/arrivals_and_departures_for_stop_handler.go", "", "resolved", "restates 3741249976", False),
    (1313, 5227370818, 2, "design", "Singular arrival-and-departure-for-stop changed without a dedicated test.", "internal/restapi/situation_references_test.go", "", "resolved", "restates 3741251478", False),
    (1313, 5289688920, 1, "process_other", "Please fix merge conflicts.", "", "", "resolved", "", False),
    (1313, 3741249976, 1, "defect", "Dedupe on agency-scoped situation ID duplicates the same alert under two prefixes.", "internal/restapi/arrivals_and_departures_for_stop_handler.go", "", "resolved", "same as 5227370818-1", False),
    (1313, 3741251478, 1, "design", "Add an arrival-and-departure-for-stop situation-reference case.", "internal/restapi/situation_references_test.go", "", "resolved", "same as 5227370818-2", False),
    (1313, 3741252614, 1, "design", "Idempotent prefixing diverges from Java and FormCombinedID; document, no code change required.", "internal/restapi/reference_utils.go", "", "resolved", "reviewer said no change needed", False),
    (1313, 3771182769, 1, "design", "TripSituations re-resolves alerts BuildTripStatus already loaded on trip-details.", "internal/restapi/trip_details_handler.go", "", "resolved", "", True),
    (1313, 3771182775, 1, "design", "Same duplicate TripSituations lookup on trip-for-vehicle.", "internal/restapi/trip_for_vehicle_handler.go", "", "resolved", "", True),
    (1313, 3771182780, 1, "design", "Same duplicate TripSituations lookup on arrival-and-departure-for-stop.", "internal/restapi/arrival_and_departure_for_stop_handler.go", "", "resolved", "", True),
    (1313, 3771182784, 1, "design", "GetSituationIDsForTrip should delegate to TripSituations instead of copying the loop.", "internal/restapi/trips_helper.go", "", "resolved", "", True),
    (1313, 3771182788, 1, "design", "DUPLICATED trips miss tripsByID so situation lookups always hit the DB.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "", True),
    (1313, 3771182794, 1, "defect", "Missing routeAgencyMap entry yields a bare unprefixed alert ID.", "internal/restapi/trips_for_route_handler.go", "", "ambiguous", "reviewer asked for a second look and said not necessarily blocking; reachability unclear. Excluded from gold until resolved.", False),
    (1313, 4922067762, 1, "process_other", "Stage-2 summary pointing at the redundant-lookup inlines.", "", "", "resolved", "", False),
    # 1315
    (1315, 5230249974, 1, "process_other", "Claude-authored 'no issues found' comment posted by a human login.", "", "", "resolved", "", False),
    (1315, 5243793949, 1, "process_other", "Coordination note that #1329 covers remaining multi-timezone work.", "", "", "resolved", "", False),
    (1315, 5288332756, 1, "process_other", "Claude-authored 'no issues found' comment posted by a human login.", "", "", "resolved", "", False),
    (1315, 4890748165, 1, "design", "agencyLocations LoadLocation is uncached and runs even when includeSchedule is false.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "reviewer deferred to follow-up", False),
    (1315, 4890748165, 2, "defect", "serviceDate stays first-agency midnight while timeZone is now per-agency.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "reviewer said not a regression; follow-up", False),
    (1315, 4890748165, 3, "process_other", "Must land after #1313/#1314.", "", "", "resolved", "", False),
    (1315, 4933041320, 1, "process_other", "Re-approval blocked on stack conflicts inherited from #1313.", "", "", "resolved", "", False),
    # 1316
    (1316, 5230257749, 1, "defect", "runsOn uses strict containment while handlers select by overlap, so fringe overnight trips still get today's midnight.", "internal/restapi/trips_helper.go", "", "resolved", "", True),
    (1316, 5288336175, 1, "style", "resolveDuplicatedBaseTrip was inserted under stripNumericSuffix's godoc.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "", False),
    (1316, 5339268579, 1, "design", "newServiceDateResolver has no callers and lands dead untested code.", "internal/restapi/trips_helper.go", "", "resolved", "", True),
    (1316, 5349606479, 1, "process_other", "Wiki note on trips-for-location window; no code change.", "", "", "resolved", "", False),
    (1316, 3801280442, 1, "design", "Delete unused newServiceDateResolver.", "internal/restapi/trips_helper.go", "", "resolved", "same as 5339268579", False),
    (1316, 3801283377, 1, "design", "DUPLICATED extras outside the base window fall back to query day; Java is more precise.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "reviewer said fine to merge / noting", False),
    (1316, 4890748311, 1, "defect", "runsOn containment vs overlap window mismatch.", "internal/restapi/trips_helper.go", "", "resolved", "same as 5230257749", False),
    (1316, 4890748311, 2, "design", "newServiceDateResolver re-runs GetActiveServiceIDsForDate the handler already has.", "internal/restapi/trips_helper.go", "", "resolved", "", True),
    (1316, 4890748311, 3, "process_other", "Stacked on #1313-#1315.", "", "", "resolved", "", False),
    (1316, 4933041489, 1, "style", "stripNumericSuffix lost its doc comment.", "internal/restapi/trips_for_route_handler.go", "", "resolved", "same as 5288336175", False),
    (1316, 4933041489, 2, "process_other", "Rebase onto #1329 per-agency midnight; do not reintroduce TodayMidnight.", "", "", "resolved", "", False),
    (1316, 4957537521, 1, "design", "Drop the unused newServiceDateResolver helper.", "internal/restapi/trips_helper.go", "", "resolved", "same as 5339268579", False),
    (1316, 4969840395, 1, "design", "Delete unused newServiceDateResolver before merge.", "internal/restapi/trips_helper.go", "", "resolved", "same as 5339268579", False),
    (1316, 4977927225, 1, "process_other", "Just needs Aaron's comments addressed.", "", "", "resolved", "", False),
    # 1317
    (1317, 5230255076, 1, "defect", "scheduledPositionAtTime does a GetStopsByIDs per candidate (N+1) instead of one union fetch.", "internal/restapi/trips_helper.go", "", "resolved", "", True),
    (1317, 5288357795, 1, "defect", "inServiceTripIDs passes the uncapped stop set into IN (...) and can 500 a dense bbox.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "", True),
    (1317, 5288357795, 2, "defect", "Failed hoisted stop fetch returns nil and places every candidate at shapePoints[0], yielding a silent wrong 200.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "", True),
    (1317, 5339325368, 1, "design", "TestFetchStopCoordsForStopTimes_BatchesLargeStopSets never spans two batches because IDs are deduped.", "internal/restapi/scheduled_block_helper_test.go", "", "resolved", "", True),
    (1317, 5339325368, 2, "defect", "Stop-coordinate lookup failure is still swallowed and the endpoint answers 200.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "same family as 5288357795-2", False),
    (1317, 5459088077, 1, "process_other", "Check-in: blocked by conflicts and failing tests.", "", "", "resolved", "", False),
    (1317, 3827408476, 1, "design", "Candidate discovery is trip-scoped; Java interpolates the whole block including layovers.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "", True),
    (1317, 3827408479, 1, "defect", "GetInServiceTripIDsForStops uses strict containment instead of Java/runsOn overlap slack.", "gtfsdb/query.sql", "", "resolved", "", True),
    (1317, 3827408480, 1, "defect", "ServiceIds slice is unbatched so a 900-stop batch plus many service IDs can exceed SQLite's bind limit.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "", True),
    (1317, 3827408481, 1, "design", "Move the lat/lon-in-bounds helper to internal/utils/geometry.go.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "non-blocking", False),
    (1317, 3827408483, 1, "style", "Cancellation returns visible,nil instead of clientCanceledResponse used elsewhere in the handler.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "non-blocking", False),
    (1317, 4890748341, 1, "defect", "Per-candidate GetStopsByIDs N+1.", "internal/restapi/trips_helper.go", "", "resolved", "same as 5230255076", False),
    (1317, 4890748341, 2, "design", "Shape points fetched twice per request.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "non-blocking", False),
    (1317, 4890748341, 3, "design", "Shapeless trips are silently excluded; document as a known limitation.", "", "", "resolved", "non-blocking", False),
    (1317, 4933041629, 1, "defect", "Uncapped stop set into GetInServiceTripIDsForStops.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "same as 5288357795-1", False),
    (1317, 4933041629, 2, "defect", "Larger unbatched stop-coord union fails silently at shape start.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "same as 5288357795-2", False),
    (1317, 4933041629, 3, "design", "scheduledPositionAtTime duplicates applyScheduledTripPositionToStatus.", "internal/restapi/trips_helper.go", "", "resolved", "non-blocking", False),
    (1317, 4933041629, 4, "design", "Live vehicle without a position is excluded from both RT and scheduled passes.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "non-blocking", False),
    (1317, 4969906202, 1, "design", "Batching test does not actually exercise multiple batches.", "internal/restapi/scheduled_block_helper_test.go", "", "resolved", "same as 5339325368-1", False),
    (1317, 4969906202, 2, "defect", "fetchStopCoordsForStopTimes still has no error path to the handler.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "same as 5288357795-2", False),
    (1317, 4989835326, 1, "process_other", "Round-3 summary pointing at Java-conformance inlines.", "", "", "resolved", "", False),
    # 1329
    (1329, 5288323142, 1, "process_other", "Claude-authored 'no issues found' comment posted by a human login.", "", "", "resolved", "", False),
    (1329, 4933040824, 1, "process_other", "Approval of bugs already fixed in this PR; remaining items are non-blocking follow-ups.", "", "", "resolved", "clean-change on remaining issues", False),
    (1329, 4933040824, 2, "design", "Move serviceDateMidnight to timezone_helper.go for reuse.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "reviewer said non-blocking follow-up", False),
    (1329, 4933040824, 3, "design", "Cache agency timezone LoadLocation results.", "internal/restapi/trips_for_location_handler.go", "", "resolved", "reviewer said non-blocking follow-up", False),
    # 1347
    (1347, 5314064685, 1, "process_other", "Rebase/squash so the commit subject does not contain a literal \\n.", "", "", "resolved", "", False),
    (1347, 5339161176, 1, "process_other", "Claude-authored 'no issues found' comment posted by a human login.", "", "", "resolved", "", False),
    (1347, 3794252743, 1, "design", "Test does not pin reuse of status.SituationIDs; it still passes on pre-change code.", "internal/restapi/arrivals_and_departures_for_stop_handler_test.go", "", "resolved", "", True),
    (1347, 4948889647, 1, "design", "Test does not pin reuse of status.SituationIDs; it still passes on pre-change code.", "internal/restapi/arrivals_and_departures_for_stop_handler_test.go", "", "resolved", "restates 3794252743", False),
    (1347, 4948889647, 2, "style", "statusExtras.snapshot vs situations read-site consistency nit; reviewer said no change needed.", "internal/restapi/arrivals_and_departures_for_stop_handler.go", "", "resolved", "", False),
    (1347, 4948889647, 3, "process_other", "Commit message body has literal \\n instead of newlines.", "", "", "resolved", "", False),
    (1347, 4969730321, 1, "design", "Test does not pin reuse of status.SituationIDs.", "internal/restapi/arrivals_and_departures_for_stop_handler_test.go", "", "resolved", "restates 3794252743", False),
    (1347, 4969730321, 2, "design", "GetAlertsForTrip will have no production callers after this PR; delete in a follow-up.", "", "", "resolved", "reviewer said not this PR", False),
    # 1348
    (1348, 3801674253, 1, "defect", "freqs[0] ignores which frequency window is applicable at query time.", "internal/restapi/trips_helper.go", "", "resolved", "", True),
    (1348, 3801674344, 1, "defect", "Frequency-only route/direction emits scheduleStopTimes: null instead of [].", "internal/restapi/schedule_for_stop_handler.go", "", "resolved", "", True),
    (1348, 3801674449, 1, "defect", "Seeding freqMap[id]=nil before the batch query hides GetFrequenciesForTrips errors as no-frequency.", "internal/restapi/arrivals_and_departures_for_stop_handler.go", "", "resolved", "", True),
    (1348, 3801678351, 1, "defect", "freqs[0] ignores which frequency window is applicable at query time.", "internal/restapi/trips_helper.go", "", "resolved", "duplicate post of 3801674253", False),
    (1348, 3801678897, 1, "defect", "Frequency-only route/direction emits scheduleStopTimes: null instead of [].", "internal/restapi/schedule_for_stop_handler.go", "", "resolved", "duplicate post of 3801674344", False),
    (1348, 3801679012, 1, "defect", "Seeding freqMap[id]=nil before the batch query hides GetFrequenciesForTrips errors as no-frequency.", "internal/restapi/arrivals_and_departures_for_stop_handler.go", "", "resolved", "duplicate post of 3801674449", False),
    (1348, 3801679108, 1, "defect", "Singular arrival-and-departure-for-stop swallows freqErr and can 200 with frequency: null.", "internal/restapi/arrival_and_departure_for_stop_handler.go", "", "resolved", "", True),
    (1348, 3801679198, 1, "defect", "CANCELED early-return drops status.frequency while the enclosing entry still has Frequency.", "internal/restapi/trips_helper.go", "", "resolved", "", True),
    (1348, 3801679279, 1, "defect", "Unbounded GetFrequenciesForTrips bind vars can 500 a busy stop.", "internal/restapi/schedule_for_stop_handler.go", "", "resolved", "", True),
    (1348, 3801679361, 1, "design", "includeStatus path fetches GetFrequenciesForTrip a second time after BuildTripStatus.", "internal/restapi/trip_for_vehicle_handler.go", "", "resolved", "", True),
    (1348, 3817569136, 1, "defect", "freqs[0] ignores which frequency window is applicable at query time.", "internal/restapi/trips_helper.go", "", "resolved", "burma restatement of 3801674253", False),
    (1348, 3817569144, 1, "defect", "CANCELED early-return drops status.frequency.", "internal/restapi/trips_helper.go", "", "resolved", "burma restatement of 3801679198", False),
    (1348, 3817569148, 1, "defect", "Unbounded GetFrequenciesForTrips bind vars can 500 a busy stop.", "internal/restapi/schedule_for_stop_handler.go", "", "resolved", "burma restatement of 3801679279", False),
    (1348, 3817569148, 2, "design", "Four copy-pasted batch-seed blocks should be one helper.", "internal/restapi/schedule_for_stop_handler.go", "", "resolved", "", True),
    (1348, 3817569159, 1, "defect", "Seeding freqMap[id]=nil before the batch query hides GetFrequenciesForTrips errors as no-frequency.", "internal/restapi/arrivals_and_departures_for_stop_handler.go", "", "resolved", "burma restatement of 3801674449", False),
    (1348, 3817569166, 1, "defect", "Frequency-only route/direction emits scheduleStopTimes: null instead of [].", "internal/restapi/schedule_for_stop_handler.go", "", "resolved", "burma restatement of 3801674344", False),
    (1348, 3817569172, 1, "design", "exact_times=1 headway expansion is uncapped and can explode large windows.", "internal/restapi/schedule_for_stop_handler.go", "", "resolved", "", True),
    (1348, 3817569177, 1, "defect", "Singular arrival-and-departure-for-stop swallows freqErr.", "internal/restapi/arrival_and_departure_for_stop_handler.go", "", "resolved", "burma restatement of 3801679108", False),
    (1348, 3817569182, 1, "defect", "BuildTripStatus/BuildTripSchedule errors now 500 trip-for-vehicle instead of degrading to null.", "internal/restapi/trip_for_vehicle_handler.go", "", "resolved", "", True),
    (1348, 3817569186, 1, "design", "includeStatus path fetches GetFrequenciesForTrip a second time after BuildTripStatus.", "internal/restapi/trip_for_vehicle_handler.go", "", "resolved", "burma restatement of 3801679361", False),
    (1348, 4958117872, 1, "process_other", "Please fix the items noted in the inline review.", "", "", "resolved", "", False),
    (1348, 4977743941, 1, "defect", "freqs[0] ignores which frequency window is applicable at query time.", "internal/restapi/trips_helper.go", "", "resolved", "review-body restatement of 3801674253", False),
    (1348, 4977743941, 2, "process_other", "Wiki decision: keep exact_times=1 expansion as documented; no code change.", "", "", "resolved", "", False),
    (1348, 4990218481, 1, "process_other", "Merge-conflict nag.", "", "", "resolved", "", False),
    # 1352
    (1352, 5339058790, 1, "process_other", "Claude-authored 'no issues found' comment posted by a human login.", "", "", "resolved", "", False),
    (1352, 5339112074, 1, "process_other", "Approval blocked on merge conflicts after #1351 landed.", "", "", "resolved", "", False),
    (1352, 5361504853, 1, "process_other", "Wiki FYI; no code change requested.", "", "", "resolved", "", False),
    (1352, 4969643941, 1, "style", "Stale comment still says queryTime after the rename.", "internal/restapi/stops_for_location_handler.go", "", "resolved", "reviewer marked non-blocking", False),
    (1352, 4969643941, 2, "process_other", "Approval / merging.", "", "", "resolved", "complimentary", False),
    # 1359
    (1359, 5339061617, 1, "design", "Test pins 600m as the spec default; Java/spec default is 500m.", "internal/restapi/routes_for_location_handler_test.go", "", "resolved", "", True),
    (1359, 4957854608, 1, "design", "Change DefaultSearchRadiusInMeters from 600 to 500.", "internal/models/", "", "resolved", "same 600-vs-500 issue; later review said not in this PR", False),
    (1359, 4969639462, 1, "design", "Do not lock 600m as the spec default; do not flip the shared constant in this PR.", "internal/restapi/routes_for_location_handler_test.go", "", "resolved", "restates 5339061617", False),
    (1359, 4969639462, 2, "style", "Fold maxCount=0 message assertion into the existing table-driven test.", "internal/restapi/routes_for_location_handler_test.go", "", "resolved", "reviewer marked non-blocking", False),
    (1359, 4969639462, 3, "style", "Comment claims the spec quotes a fieldErrors string that lives only in code.", "internal/restapi/routes_for_location_handler_test.go", "", "resolved", "reviewer marked non-blocking", False),
    # 1372
    (1372, 4998300230, 1, "design", "stop_agencies should store one row per (stop, agency), not one row per stop.", "", "", "resolved", "", True),
    (1372, 4999944911, 1, "process_other", "Same opinion as @burma-shave; no independent issue.", "", "", "resolved", "", False),
    # 1375
    (1375, 5456003071, 1, "process_other", "Reminder to run make test.", "", "", "resolved", "", False),
    (1375, 5463835518, 1, "process_other", "LGTM; verified against spec. No remaining issue.", "", "", "resolved", "clean-change note", False),
    # 1380
    (1380, 5406230648, 1, "process_other", "Please fix format and SonarQube Cloud issues.", "", "", "resolved", "", False),
    (1380, 5055722905, 1, "defect", "references.agencies omits owners of cross-agency routes returned in references.routes.", "internal/restapi/", "", "resolved", "", True),
    (1380, 5093782675, 1, "defect", "stops-for-route still omits owners of cross-agency route references.", "internal/restapi/stops_for_route_handler.go", "", "resolved", "", True),
    (1380, 5093782675, 2, "design", "trip-details may also omit a referenced agency on a schedule-reference path.", "internal/restapi/trip_details_handler.go", "", "resolved", "reviewer said may also; not asserted as required here", False),
    # 1385
    (1385, 5377006205, 1, "process_other", "Request for a CodeRabbit review.", "", "", "resolved", "", False),
    (1385, 5459088193, 1, "process_other", "Stack check-in: address requested changes on the base PR first.", "", "", "resolved", "", False),
    (1385, 5548284191, 1, "process_other", "Duplicate stack check-in.", "", "", "resolved", "", False),
    (1385, 3834719282, 1, "design", "ValidateServiceDate duplicates unused ValidateDate instead of replacing it.", "internal/utils/validation.go", "", "resolved", "", True),
    (1385, 3834719284, 1, "design", "Second ParseDate after ValidateServiceDate is dead; comment is inaccurate.", "internal/restapi/schedule_for_stop_handler.go", "", "resolved", "", True),
    (1385, 4998546853, 1, "process_other", "Pointer to the two inline findings; out-of-diff items excluded.", "", "", "resolved", "", False),
    (1385, 5035869775, 1, "process_other", "API-review write-up: stated goal already closed; no new issue.", "", "", "resolved", "complimentary / process", False),
    # 1386
    (1386, 3849948222, 1, "design", "Optional guard for headway==0 so a unit test cannot panic.", "internal/restapi/schedule_for_stop_handler.go", "", "resolved", "reviewer marked optional / not blocking", False),
    (1386, 3849954463, 1, "design", "FormCombinedID should use route.AgencyID; pre-existing and not blocking.", "internal/restapi/schedule_for_stop_handler.go", "", "resolved", "pre-existing / not blocking", False),
    (1386, 5014781857, 1, "process_other", "Approval; optional notes already recorded on inlines.", "", "", "resolved", "complimentary", False),
    # 1404
    (1404, 3884272420, 1, "design", "agencyTimezone reimplements LoadLocation instead of reusing loadAgencyLocation.", "internal/restapi/current_time_handler.go", "", "resolved", "", True),
    (1404, 3884272420, 2, "defect", "Failed timezone load is silently swallowed and falls back to UTC with no operator log.", "internal/restapi/current_time_handler.go", "", "resolved", "", True),
    (1404, 3884272424, 1, "design", "Missing tests for the three agencyTimezone fallback branches.", "internal/restapi/current_time_handler_test.go", "", "resolved", "", True),
    (1404, 5055352159, 1, "process_other", "Code review findings pointer to inlines.", "", "", "resolved", "", False),
    # 1407
    (1407, 5055923018, 1, "defect", "Frequency support is missing versus main; stop arrivals emit frequency: null.", "internal/restapi/arrivals_core.go", "", "resolved", "", True),
    (1407, 5055923018, 2, "defect", "GetStopsByIDs failure now hard-500s instead of degrading with incomplete stop references.", "internal/restapi/arrivals_core.go", "", "resolved", "", True),
    (1407, 5055923018, 3, "design", "RouteTypes / isRouteTypeAllowed is never wired and adds dead hot-path code.", "internal/restapi/arrivals_core.go", "", "resolved", "", True),
    (1407, 5055923018, 4, "design", "arrivalsReferencesInput.stopAgencies is never populated.", "internal/restapi/arrivals_core.go", "", "resolved", "", True),
    (1407, 5055923018, 5, "design", "Route/stop reference building bypasses reference_utils helpers.", "internal/restapi/arrivals_core.go", "", "resolved", "", True),
    (1407, 5055923018, 6, "design", "Singular arrival-and-departure handler still duplicates the extracted reference logic.", "internal/restapi/arrival_and_departure_for_stop_handler.go", "", "resolved", "reviewer said follow-up", False),
    (1407, 5055923018, 7, "design", "alertAgencyID is a single scalar despite the accumulator being documented as multi-stop.", "internal/restapi/arrivals_core.go", "", "ambiguous", "reviewer said worth flagging; requested changes were primarily items 1-2. Excluded from gold until resolved.", False),
    # 1428
    (1428, 5151390767, 1, "design", "Assert DistanceAlongBlock through callAPIHandler / real GetBlockDetails instead of hand-built rows.", "internal/restapi/block_handler_test.go", "", "resolved", "", True),
    (1428, 5599665947, 1, "defect", "Unused gtfsdb import in block_handler_test.go fails go vet.", "internal/restapi/block_handler_test.go", "", "resolved", "", True),
]
